name: DEV Deployment
on:
  workflow_dispatch:
  push:
    branches: [ "development" ]

jobs:
  trigger:
    uses: zakkumohd/configurations/.github/workflows/html.yml@develop
    with:
      ECR_REGISTRY: ${{vars.ECR_REGISTRY}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
      CONTAINER_NAME: ${{vars.CONTAINER_NAME}}
    
    secrets: inherit
